### PR TITLE
Remove Weeds

### PR DESCRIPTION
**Pull request by dMARLAN**
Remove references to weeds -- AIC shouldn't use "weeds" more of an AUX comm for fighters.

### CODE REVIEW

**Comment by dharmab** [comment]
Re-apply this patch on top of #96, there was a problem on `main` that IntelliJ was trying to fix here haha. #98 should prevent it in the future.

**Comment by dharmab** [comment]
Also let me know once you've tested this manually- connect it to Hoggit, run a picture, double check it works as expected. (Not that this change is risky, but it's a good habit.)

**Comment by dharmab** [comment]
```bash
git fetch origin
git rebase origin/main --ignore-whitespace
git push --force
```

That should fix it

**Comment by dharmab** [comment]
I had to touch part of this in #59 but there's still cleanup to do

**Comment by dMARLAN** [comment]
I will handle this eventually, been very busy lol

**Comment by dharmab** [comment]
LGTM,

**Pull request merged**
