### PR TITLE
Add a scaler tool

### LINKED ISSUE #230: Create autoscaler
Create a small tool which monitors the SRS channel. When a player joins, it runs a hook to scale up a SkyEye instance. When no players have been on the channel for 10 minutes, scale down the instance.

### PR DESCRIPTION
**Pull request by dharmab**
Closes #230

### CODE REVIEW

**Comment by Rabbit994** [comment]
I've been ignoring Discord for past week. What's the status on this PR?

**Comment by dharmab** [comment]
After I messaged you I set it aside to work on other stuff 😅 

I just rebased this MR, fixed a couple of things and tested it using httpbin to receive the webhook. It seemed to work fine.

Here's a compiled EXE file if you want to test it out. If it works well I'll polish this up and get it merged. 

[skyeye-scaler.zip](https://github.com/user-attachments/files/17007080/skyeye-scaler.zip)

**Comment by Rabbit994** [comment]
Thanks, I got the exe and I'm starting to build my scaler.

Couple of things I've noticed so far.

It constantly sends "up" and "down". Just need to decide if that's intended behavior, I'll keep state in local SQLite database.

If it starts up and sees people on the channel, it won't run up/down until after scale interval kicks in. Therefore, I set scale interval to 15s. 

WebHook URL isn't well documented, I figured it out but it took 5 minutes of command line screaming.

HTTP Timeout is too high. 30s and it needs to timeout.

The post request not being JSON is no bueno. I consider this a bug (:bug:) from my POV but I'm working around it.

Including SRS Server IP in POST Body would be grant. Just in case you have multiple of them sending to same URL, the end state application can handle it.

I assume Linux build will be available once it's "prod" but Windows is working fine for Dev work.

**Comment by dharmab** [comment]
Thanks for the feedback, made these changes:

- scaler now sends a request on startup before starting the loop
- requests have a configurable timeout, default 10s
- switched from URL parameters to a JSON body. Fields are documented in ADMIN.md
  - body now includes the SRS server address and a list of radio frequencies

> It constantly sends "up" and "down". Just need to decide if that's intended behavior, I'll keep state in local SQLite database.

Yup. That way an implementation doesn't have to have a database or maintain much state.

> I assume Linux build will be available once it's "prod" but Windows is working fine for Dev work.

If you'd prefer a Linux build, install Go 1.23 or newer, then follow the instructions [here](https://github.com/dharmab/skyeye/blob/main/docs/CONTRIBUTING.md#linux). Or if you'd prefer not to install the compiler and libraries, build the container image from this branch with `docker build . -t skyeye:dev`, it includes the scaler at `/opt/skyeye/bin/skyeye-scaler`.

[skyeye-scaler.zip](https://github.com/user-attachments/files/17007803/skyeye-scaler.zip)

**Comment by Rabbit994** [comment]
Update on my end. My scaler is working but it's in beta so it's not source available. I need to move from Azure DevOps to GitHub so I can provide a public container.

Only open "bug" is frequency post not providing modulation. At this point, I feel like it be a breaking API change to put it in but it probably should.

Single Container with both executables is not ideal but it's easy to handle since I can just override entry point.

**Comment by dharmab** [comment]
- Changed `frequencies` field to directly pass through the strings for `--srs-frequencies`
- Updated GitHub Actions to build the scaler into a separate container image (I hope... will find out duringthe next release!)

**Pull request merged**
